echo -- Services

echo -- Disabling Manual Services
sc config AppIDSvc start=demand
sc config AppMgmt start=demand
sc config AppReadiness start=demand
sc config AppVClient start=disabled
sc config AppXSvc start=demand
sc config Appinfo start=demand
sc config AssignedAccessManagerSvc start=disabled
sc config AxInstSV start=demand
sc config BTAGService start=demand
sc config BcastDVRUserService start=demand
sc config BluetoothUserService start=demand
sc config Browser start=demand
sc config CDPSvc start=demand
sc config COMSysApp start=demand
sc config CaptureService start=demand
sc config ClipSVC start=demand
sc config ConsentUxUserSvc start=demand
sc config DevQueryBroker start=demand
sc config DeviceAssociationService start=demand
sc config DeviceInstall start=demand
sc config DevicePickerUserSvc start=demand
sc config DevicesFlowUserSvc start=demand
sc config DialogBlockingService start=disabled
sc config DisplayEnhancementService start=demand
sc config DmEnrollmentSvc start=demand
sc config DsSvc start=demand
sc config DsmSvc start=demand
sc config EFS start=demand
sc config EapHost start=demand
sc config EntAppSvc start=demand
sc config FDResPub start=demand
sc config FrameServer start=demand
sc config FrameServerMonitor start=demand
sc config GraphicsPerfSvc start=demand
sc config HvHost start=demand
sc config IEEtwCollectorService start=demand
sc config InstallService start=demand
sc config InventorySvc start=demand
sc config IpxlatCfgSvc start=demand
sc config KtmRm start=demand
sc config LicenseManager start=demand
sc config LxpSvc start=demand
sc config MSDTC start=demand
sc config MSiSCSI start=demand
sc config McpManagementService start=demand
sc config MessagingService start=demand
sc config MicrosoftEdgeElevationService start=demand
sc config MsKeyboardFilter start=demand
sc config NPSMSvc start=demand
sc config NaturalAuthentication start=demand
sc config NcaSvc start=demand
sc config NcbService start=demand
sc config NcdAutoSetup start=demand
sc config NetSetupSvc start=demand
sc config NetTcpPortSharing start=disabled
sc config Netman start=demand
sc config NgcCtnrSvc start=demand
sc config NgcSvc start=demand
sc config NlaSvc start=demand
sc config P9RdrService start=demand
sc config PNRPAutoReg start=demand
sc config PNRPsvc start=demand
sc config PeerDistSvc start=demand
sc config PenService start=demand
sc config PerfHost start=demand
sc config PimIndexMaintenanceSvc start=demand
sc config PlugPlay start=demand
sc config PolicyAgent start=demand
sc config PrintNotify start=demand
sc config PushToInstall start=demand
sc config QWAVE start=demand
sc config RasAuto start=demand
sc config RasMan start=demand
sc config RemoteAccess start=disabled
sc config RmSvc start=demand
sc config RpcLocator start=demand
sc config SDRSVC start=demand
sc config SEMgrSvc start=demand
sc config SNMPTRAP start=demand
sc config SNMPTrap start=demand
sc config SSDPSRV start=demand
sc config SensorDataService start=demand
sc config SensrSvc start=demand
sc config SharedAccess start=demand
sc config SmsRouter start=demand
sc config SstpSvc start=demand
sc config StiSvc start=demand
sc config StateRepository start=demand
sc config StorSvc start=demand
sc config TextInputManagementService start=demand
sc config TieringEngineService start=demand
sc config TokenBroker start=demand
sc config TroubleshootingSvc start=demand
sc config TrustedInstaller start=demand
sc config UdkUserSvc start=demand
sc config UmRdpService start=demand
sc config UnistoreSvc start=demand
sc config UserDataSvc start=demand
sc config UsoSvc start=demand
sc config VSS start=demand
sc config VacSvc start=demand
sc config WEPHOSTSVC start=demand
sc config WFDSConMgrSvc start=demand
sc config WMPNetworkSvc start=demand
sc config WManSvc start=demand
sc config WPDBusEnum start=demand
sc config WarpJITSvc start=demand
sc config WdNisSvc start=demand
sc config WdiServiceHost start=demand
sc config WebClient start=demand
sc config Wecsvc start=demand
sc config WiaRpc start=demand
sc config WinHttpAutoProxySvc start=demand
sc config WinRM start=demand
sc config WpnService start=demand
sc config WwanSvc start=demand
sc config autotimesvc start=demand
sc config bthserv start=demand
sc config camsvc start=demand
sc config cbdhsvc start=demand
sc config cloudidsvc start=demand
sc config dcsvc start=demand
sc config defragsvc start=demand
sc config diagnosticshub.standardcollector.service start=demand
sc config dmwappushservice start=demand
sc config dot3svc start=demand
sc config edgeupdate start=demand
sc config edgeupdatem start=demand
sc config embeddedmode start=demand
sc config fdPHost start=demand
sc config fhsvc start=demand
sc config hidserv start=demand
sc config lltdsvc start=demand
sc config msiserver start=demand
sc config netprofm start=demand
sc config p2pimsvc start=demand
sc config p2psvc start=demand
sc config perceptionsimulation start=demand
sc config pla start=demand
sc config shpamsvc start=disabled
sc config smphost start=demand
sc config ssh-agent start=disabled
sc config svsvc start=demand
sc config swprv start=demand
sc config tzautoupdate start=disabled
sc config upnphost start=demand
sc config vds start=demand
sc config vmicguestinterface start=demand
sc config vmicheartbeat start=demand
sc config vmickvpexchange start=demand
sc config vmicrdv start=demand
sc config vmicshutdown start=demand
sc config vmictimesync start=demand
sc config vmicvmsession start=demand
sc config vmicvss start=demand
sc config vmvss start=demand
sc config wbengine start=demand
sc config wcncsvc start=demand
sc config webthreatdefsvc start=demand
sc config wercplsupport start=demand
sc config wlidsvc start=demand
sc config wlpasvc start=demand
sc config wmiApSrv start=demand
sc config wuauserv start=demand
sc config wudfsvc start=demand

net stop SysMain /y >nul 2>&1 && sc config SysMain start= disabled >nul 2>&1 && echo SysMain - Stopped and disabled
net stop AsusUpdateCheck /y >nul 2>&1 && sc config AsusUpdateCheck start= disabled >nul 2>&1 && echo AsusUpdateCheck - Stopped and disabled
net stop XboxGipSvc /y >nul 2>&1 && sc config XboxGipSvc start= disabled >nul 2>&1 && echo XboxGipSvc - Stopped and disabled
net stop WSearch /y >nul 2>&1 && sc config WSearch start= disabled >nul 2>&1 && echo WSearch - Stopped and disabled
net stop XboxNetApiSvc /y >nul 2>&1 && sc config XboxNetApiSvc start= disabled >nul 2>&1 && echo XboxNetApiSvc - Stopped and disabled
net stop MapsBroker /y >nul 2>&1 && sc config MapsBroker start= disabled >nul 2>&1 && echo MapsBroker - Stopped and disabled
net stop WdiSystemHost /y >nul 2>&1 && sc config WdiSystemHost start= disabled >nul 2>&1 && echo WdiSystemHost - Stopped and disabled
net stop SensorService /y >nul 2>&1 && sc config SensorService start= disabled >nul 2>&1 && echo SensorService - Stopped and disabled
net stop WalletService /y >nul 2>&1 && sc config WalletService start= disabled >nul 2>&1 && echo WalletService - Stopped and disabled
net stop TermService /y >nul 2>&1 && sc config TermService start= disabled >nul 2>&1 && echo TermService - Stopped and disabled
net stop TapiSrv /y >nul 2>&1 && sc config TapiSrv start= disabled >nul 2>&1 && echo TapiSrv - Stopped and disabled
net stop PhoneSvc /y >nul 2>&1 && sc config PhoneSvc start= disabled >nul 2>&1 && echo PhoneSvc - Stopped and disabled
net stop Spooler /y >nul 2>&1 && sc config Spooler start= disabled >nul 2>&1 && echo Spooler - Stopped and disabled
net stop WpcMonSvc /y >nul 2>&1 && sc config WpcMonSvc start= disabled >nul 2>&1 && echo WpcMonSvc - Stopped and disabled
net stop Fax /y >nul 2>&1 && sc config Fax start= disabled >nul 2>&1 && echo Fax - Stopped and disabled
net stop DiagTrack /y >nul 2>&1 && sc config DiagTrack start= disabled >nul 2>&1 && echo DiagTrack - Stopped and disabled
net stop BthAvctpSvc /y >nul 2>&1 && sc config BthAvctpSvc start= disabled >nul 2>&1 && echo BthAvctpSvc - Stopped and disabled
net stop RemoteRegistry /y >nul 2>&1 && sc config RemoteRegistry start= disabled >nul 2>&1 && echo RemoteRegistry - Stopped and disabled
net stop WbioSrvc /y >nul 2>&1 && sc config WbioSrvc start= disabled >nul 2>&1 && echo WbioSrvc - Stopped and disabled
net stop dmwappushservice /y >nul 2>&1 && sc config dmwappushservice start= disabled >nul 2>&1 && echo dmwappushservice - Stopped and disabled
net stop lfsvc /y >nul 2>&1 && sc config lfsvc start= disabled >nul 2>&1 && echo lfsvc - Stopped and disabled
net stop TabletInputService /y >nul 2>&1 && sc config TabletInputService start= disabled >nul 2>&1 && echo TabletInputService - Stopped and disabled
net stop ALG /y >nul 2>&1 && sc config ALG start= disabled >nul 2>&1 && echo ALG - Stopped and disabled
net stop AJRouter /y >nul 2>&1 && sc config AJRouter start= disabled >nul 2>&1 && echo AJRouter - Stopped and disabled
net stop CertPropSvc /y >nul 2>&1 && sc config CertPropSvc start= disabled >nul 2>&1 && echo CertPropSvc - Stopped and disabled
net stop CscService /y >nul 2>&1 && sc config CscService start= disabled >nul 2>&1 && echo CscService - Stopped and disabled
net stop RetailDemo /y >nul 2>&1 && sc config RetailDemo start= disabled >nul 2>&1 && echo RetailDemo - Stopped and disabled
net stop seclogon /y >nul 2>&1 && sc config seclogon start= disabled >nul 2>&1 && echo seclogon - Stopped and disabled
net stop SCardSvr /y >nul 2>&1 && sc config SCardSvr start= disabled >nul 2>&1 && echo SCardSvr - Stopped and disabled
net stop SCPolicySvc /y >nul 2>&1 && sc config SCPolicySvc start= disabled >nul 2>&1 && echo SCPolicySvc - Stopped and disabled
net stop ScDeviceEnum /y >nul 2>&1 && sc config ScDeviceEnum start= disabled >nul 2>&1 && echo ScDeviceEnum - Stopped and disabled
net stop DPS /y >nul 2>&1 && sc config DPS start= disabled >nul 2>&1 && echo DPS - Stopped and disabled
net stop Netlogon /y >nul 2>&1 && sc config Netlogon start= disabled >nul 2>&1 && echo Netlogon - Stopped and disabled
net stop wisvc /y >nul 2>&1 && sc config wisvc start= disabled >nul 2>&1 && echo wisvc - Stopped and disabled
net stop icssvc /y >nul 2>&1 && sc config icssvc start= disabled >nul 2>&1 && echo icssvc - Stopped and disabled
net stop SessionEnv /y >nul 2>&1 && sc config SessionEnv start= disabled >nul 2>&1 && echo SessionEnv - Stopped and disabled
net stop PcaSvc /y >nul 2>&1 && sc config PcaSvc start= disabled >nul 2>&1 && echo PcaSvc - Stopped and disabled
net stop BDESVC /y >nul 2>&1 && sc config BDESVC start= disabled >nul 2>&1 && echo BDESVC - Stopped and disabled
net stop lmhosts /y >nul 2>&1 && sc config lmhosts start= disabled >nul 2>&1 && echo lmhosts - Stopped and disabled
net stop diagsvc /y >nul 2>&1 && sc config diagsvc start= disabled >nul 2>&1 && echo diagsvc - Stopped and disabled
net stop pla /y >nul 2>&1 && sc config pla start= disabled >nul 2>&1 && echo pla - Stopped and disabled
net stop workfolderssvc /y >nul 2>&1 && sc config workfolderssvc start= disabled >nul 2>&1 && echo workfolderssvc - Stopped and disabled
net stop WerSvc /y >nul 2>&1 && sc config WerSvc start= disabled >nul 2>&1 && echo WerSvc - Stopped and disabled

echo -- Disabling Windows Search
sc stop "wsearch" && sc config "wsearch" start=disabled
